version: '3.8'

services:
  products-list-database:
    image: mariadb:lts
    container_name: products-list-database
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_PASSWORD=$MYSQLDB_PASSWORD
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - mysql-data:/var/lib/mysql

  products-list-backend:
    depends_on:
      - products-list-database
    container_name: products-list-backend
    build:
      context: .
      # dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
      - $DEBUG_LOCAL_PORT:$DEBUG_DOCKER_PORT
    environment:
      - SERVER_PORT=$PORT
      - NODE_ENV=$NODE_ENV
      - DATABASE_URL=$DATABASE_URL
    volumes:
      - /app/node_modules
    expose:
      - $NODE_DOCKER_PORT
    command: npm run start
    stdin_open: true
    tty: true

  products-list-adminer:
    image: adminer
    container_name: products-list-adminer
    env_file: ./.env
    ports:
      - $ADMINER_LOCAL_PORT:$ADMINER_DOCKER_PORT
    expose:
      - $ADMINER_DOCKER_PORT

volumes:
  mysql-data:
